# fly.toml app configuration file generated for sh0rtl-ink on 2024-06-29T16:24:59-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sh0rtl-ink'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
